export const collections = {
  tenants: 'tenants', users: 'users', authSessions: 'auth_sessions', passwordResetTokens: 'password_reset_tokens', patients: 'patients',
  careRelationships: 'care_relationships', programEnrollments: 'program_enrollments', consents: 'consents',
  devices: 'devices', pairings: 'device_pairings', assignments: 'device_assignments', credentials: 'device_credentials',
  deviceConfigurations: 'device_configurations', deviceTelemetry: 'device_telemetry',
  carePlans: 'care_plans', medicationPlans: 'medication_plans', reminderRules: 'reminder_rules',
  reminderOccurrences: 'reminder_occurrences', caregiverTasks: 'caregiver_tasks',
  sessions: 'sessions', sessionEvents: 'session_events', transcriptTurns: 'transcript_turns', artifacts: 'artifacts',
  processingRuns: 'processing_runs', qualityAssessments: 'quality_assessments', identityLinks: 'identity_links',
  featureSnapshots: 'feature_snapshots', sessionObservations: 'session_observations', featureEmbeddings: 'feature_embeddings',
  operationalBaselines: 'operational_baselines', dailyStatuses: 'daily_statuses', awayPeriods: 'away_periods',
  manualFlags: 'manual_flags', baselineModels: 'baseline_models', anomalyScores: 'anomaly_scores',
  monitoringWindows: 'monitoring_windows', reviewCases: 'review_cases', reviewDispositions: 'review_dispositions',
  notifications: 'notifications', notificationSuppressions: 'notification_suppressions',
  protocolRegistry: 'protocol_registry', featureRegistry: 'feature_registry', modelRegistry: 'model_registry',
  ruleRegistry: 'rule_registry', outboxEvents: 'outbox_events', eventConsumptions: 'event_consumptions',
  auditEvents: 'audit_events', idempotencyRecords: 'idempotency_records',
  toolInvocations: 'tool_invocations',
  supportThreads: 'support_threads', supportMessages: 'support_messages',
} as const
