"""Download selected TalkBank corpora and build verification manifests."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from verification.config import get_verification_settings
from verification.talkbank import TalkBankClient
from verification.talkbank_verification_data import (
    DEFAULT_VERIFICATION_CORPORA,
    load_selected_targets,
    prepare_selected_corpora,
)


def parse_args() -> argparse.Namespace:
    settings = get_verification_settings()
    parser = argparse.ArgumentParser(
        description="Prepare selected TalkBank corpora for verification."
    )
    parser.add_argument(
        "--email",
        default=None,
        help="Optional TalkBank email. Falls back to TALKBANK_EMAIL.",
    )
    parser.add_argument(
        "--password",
        default=None,
        help="Optional TalkBank password. Falls back to TALKBANK_PASSWORD.",
    )
    parser.add_argument(
        "--catalog",
        default=str(settings.data_dir / "talkbank" / "corpus_catalog.json"),
        help="TalkBank catalog JSON generated by download_talkbank.py or build_talkbank_catalog.py.",
    )
    parser.add_argument(
        "--corpus",
        action="append",
        default=[],
        help="Corpus spec like English/Lu. Can be repeated. Defaults to the six verification corpora.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Redownload media that already exists locally.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    settings = get_verification_settings()
    email = args.email or settings.talkbank_email
    password = args.password or settings.talkbank_password
    if not email or not password:
        raise RuntimeError("TalkBank credentials are required. Set TALKBANK_EMAIL and TALKBANK_PASSWORD.")

    catalog_path = Path(args.catalog).expanduser().resolve()
    if not catalog_path.exists():
        raise FileNotFoundError(f"TalkBank catalog not found: {catalog_path}")
    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))

    corpus_specs = args.corpus or list(DEFAULT_VERIFICATION_CORPORA)
    targets = load_selected_targets(catalog, corpus_specs)

    client = TalkBankClient(settings)
    try:
        client.login(email=email, password=password)
        index = prepare_selected_corpora(
            client,
            settings=settings,
            targets=targets,
            overwrite=args.overwrite,
        )
    finally:
        client.close()

    print(json.dumps(index, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
