"""Export a reusable TalkBank corpus catalog from anno_path_tree.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from verification.config import get_verification_settings
from verification.talkbank_catalog import write_talkbank_catalog


def parse_args() -> argparse.Namespace:
    settings = get_verification_settings()
    parser = argparse.ArgumentParser(description="Create verification/data/talkbank/corpus_catalog.json")
    parser.add_argument(
        "--tree",
        default=str(settings.data_dir / "talkbank" / "anno_path_tree.json"),
        help="TalkBank annotation tree JSON generated by download_talkbank.py.",
    )
    parser.add_argument(
        "--output",
        default=str(settings.data_dir / "talkbank" / "corpus_catalog.json"),
        help="Catalog output path.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    tree_path = Path(args.tree).expanduser().resolve()
    if not tree_path.exists():
        raise FileNotFoundError(f"TalkBank tree not found: {tree_path}")

    payload = json.loads(tree_path.read_text(encoding="utf-8"))
    catalog = write_talkbank_catalog(payload, Path(args.output))
    print(
        json.dumps(
            {
                "status": "ok",
                "tree_path": str(tree_path),
                "output_path": str(Path(args.output).expanduser().resolve()),
                "summary": catalog["summary"],
            },
            indent=2,
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
