import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import React, { createElement, useCallback, useState } from 'react';
import { ActivityIndicator, Linking, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, PrimaryButton, ScreenLayout, SecondaryButton } from '../../../src/components/AppUI';
import { listFamilyMessagesV1, loadCaregiverHome, type V1FamilyMessage, type V1FamilyVoiceReply } from '../../../src/lib/v1Caregiver';
import { colors, fontFamily, fontSize, radius, spacing } from '../../../src/theme';

export default function ChatThreadScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const [name, setName] = useState('Loved one'); const [messages, setMessages] = useState<V1FamilyMessage[]>([]); const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { if (!id) return; setLoading(true); try { const [home, feed] = await Promise.all([loadCaregiverHome(), listFamilyMessagesV1(id)]); setName(home.patients.find((person) => person.patientId === id)?.displayName || 'Loved one'); setMessages(feed); } finally { setLoading(false); } }, [id]);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  return <ScreenLayout><AppHeader title={name} onBack={() => router.back()} /><Text accessibilityRole="header" style={styles.title}>Messages for {name}</Text><Text style={styles.subtitle}>The paired Mirror shows a notification first. Your message is recorded as opened only after {name} chooses to view it.</Text>{loading ? <ActivityIndicator color={colors.accent} /> : null}{messages.map((message) => <View key={message.messageId} style={styles.outgoing}><Text style={styles.message}>{message.text || message.caption || message.body || (message.kind === 'voice' ? 'Voice message' : 'Family message')}</Text><Text style={styles.status}>{messageState(message.state)} · {new Intl.DateTimeFormat('en-SG', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(message.createdAt))}</Text>{message.voiceReplies?.map((reply) => <VoiceReply key={reply.replyId} reply={reply} />)}</View>)}{!loading && !messages.length ? <Text style={styles.empty}>No messages have been sent yet.</Text> : null}<View style={styles.messageActions}><PrimaryButton icon="send" label="Send text message" onPress={() => router.push(`/chat/${id}/compose`)} /><SecondaryButton icon="image" label="Send photo" onPress={() => router.push(`/chat/${id}/photo`)} /><SecondaryButton icon="mic" label="Send voice message" onPress={() => router.push(`/chat/${id}/voice`)} /></View></ScreenLayout>;
}
function messageState(state: V1FamilyMessage['state']) { return ({ scheduled: 'Scheduled', queued: 'Queued', delivered: 'Delivered to device', opened: 'Delivered to device · Viewed', expired: 'Expired', failed: 'Could not deliver' })[state]; }

function VoiceReply({ reply }: { reply: V1FamilyVoiceReply }) {
  return <View style={styles.reply}><Text style={styles.replyTitle}>{reply.senderName} replied by voice</Text><Text style={styles.replyMeta}>{reply.state} · {new Intl.DateTimeFormat('en-SG', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(reply.sentAt || reply.createdAt))}</Text>{reply.audioUrl ? <VoicePlayer url={reply.audioUrl} /> : <Text style={styles.replyUnavailable}>Audio is still becoming available.</Text>}</View>;
}

function VoicePlayer({ url }: { url: string }) {
  if (Platform.OS === 'web') return createElement('audio', { controls: true, preload: 'metadata', src: url, style: { marginTop: spacing.sm, width: '100%' } });
  return <Pressable accessibilityRole="button" onPress={() => void Linking.openURL(url)} style={styles.playButton}><Text style={styles.playText}>Play voice reply</Text></Pressable>;
}

const styles = StyleSheet.create({ title: { color: colors.text.primary, fontFamily: fontFamily.display, fontSize: fontSize.title, fontWeight: '500', marginTop: spacing.xl, minWidth: 0 }, subtitle: { color: colors.text.secondary, flexShrink: 1, fontSize: fontSize.body, lineHeight: 22, minWidth: 0 }, outgoing: { alignSelf: 'flex-end', backgroundColor: '#E7F3F0', borderRadius: radius.xl, maxWidth: '88%', minWidth: 0, padding: spacing.lg }, message: { color: colors.text.primary, flexShrink: 1, fontSize: fontSize.bodyLarge, lineHeight: 23, minWidth: 0 }, status: { color: colors.status.green, flexShrink: 1, fontSize: fontSize.caption, fontWeight: '700', marginTop: spacing.sm, minWidth: 0 }, reply: { backgroundColor: '#F7F4EE', borderColor: colors.border.subtle, borderRadius: radius.lg, borderWidth: 1, marginTop: spacing.md, padding: spacing.md }, replyTitle: { color: colors.text.primary, fontSize: fontSize.body, fontWeight: '700' }, replyMeta: { color: colors.text.tertiary, fontSize: fontSize.caption, marginTop: spacing.xs }, replyUnavailable: { color: colors.text.secondary, fontSize: fontSize.caption, marginTop: spacing.sm }, playButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.accent, borderRadius: radius.md, marginTop: spacing.sm, minHeight: 44, justifyContent: 'center', paddingHorizontal: spacing.md }, playText: { color: colors.text.onAccent, fontSize: fontSize.body, fontWeight: '700' }, empty: { color: colors.text.secondary, flexShrink: 1, fontSize: fontSize.body, minWidth: 0 }, messageActions: { gap: spacing.md, minWidth: 0, width: '100%' } });
