import { Feather } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { listFamilyMessagesV1, loadCaregiverHome, type V1FamilyMessage } from '../../src/lib/v1Caregiver';
import { colors, fontFamily, fontSize, radius, spacing } from '../../src/theme';
import { ScreenLayout } from '../../src/components/AppUI';
import { useTabBarClearance } from '../../src/lib/useTabBarClearance';

type Event = { id: string; patientId: string; title: string; detail: string; time: string; icon: 'send' | 'monitor' };
export default function ActivityScreen() {
  const router = useRouter(); const clearance = useTabBarClearance(); const [events, setEvents] = useState<Event[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const refresh = useCallback(async () => { setLoading(true); setError(''); try { const home = await loadCaregiverHome(); const feeds = await Promise.all(home.patients.map(async (person) => ({ person, messages: await listFamilyMessagesV1(person.patientId) }))); const next: Event[] = feeds.flatMap(({ person, messages }) => { const messageEvents = messages.map((message) => messageEvent(person.displayName, person.patientId, message)); const pairingEvent = person.deviceId ? [{ id: `device-${person.patientId}`, patientId: person.patientId, title: 'Device paired', detail: `${person.mirrorName || 'Reflexion Mirror'} is connected for ${person.displayName}.`, time: person.mirrorName ? 'Connected device' : 'Device connected', icon: 'monitor' as const }] : []; return [...messageEvents, ...pairingEvent]; }); setEvents(next.sort((a, b) => b.id.localeCompare(a.id))); } catch (cause) { setError(cause instanceof Error ? cause.message : 'We could not load activity. Check your connection and try again.'); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  return <ScreenLayout bottomInset={clearance} contentContainerStyle={styles.content}><View style={styles.header}><Text accessibilityRole="header" style={styles.title}>Activity</Text><View style={styles.headerActions}><TouchableOpacity accessibilityLabel="Filter activity" accessibilityRole="button" onPress={() => router.push('/activity/filter')} style={styles.filter}><Feather color={colors.accent} name="sliders" size={19} /><Text style={styles.filterText}>Filter</Text></TouchableOpacity><TouchableOpacity accessibilityLabel="Refresh activity" accessibilityRole="button" onPress={() => void refresh()} style={styles.filter}><Feather color={colors.accent} name="refresh-cw" size={19} /><Text style={styles.filterText}>Refresh</Text></TouchableOpacity></View></View><Text style={styles.subtitle}>A factual timeline of device connections and family-message delivery. Reflexion does not invent activity before a device is linked.</Text>{loading ? <ActivityIndicator color={colors.accent} /> : null}{error ? <View style={styles.empty}><Text style={styles.emptyTitle}>Activity is unavailable</Text><Text style={styles.emptyText}>{error}</Text><TouchableOpacity accessibilityRole="button" onPress={() => void refresh()} style={styles.filter}><Text style={styles.filterText}>Try again</Text></TouchableOpacity></View> : null}{!loading && !error ? events.map((event) => <TouchableOpacity key={event.id} accessibilityLabel={`${event.title}. ${event.detail}`} accessibilityRole="button" onPress={() => router.push(`/activity/${encodeURIComponent(event.id)}`)} style={styles.event}><View style={styles.dot}><Feather color={colors.accent} name={event.icon} size={15} /></View><View style={styles.eventCard}><Text style={styles.time}>{event.time}</Text><Text style={styles.eventTitle}>{event.title}</Text><Text style={styles.eventDetail}>{event.detail}</Text></View></TouchableOpacity>) : null}{!loading && !error && !events.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>No activity to show yet</Text><Text style={styles.emptyText}>Pair a device or send a family message to create the first factual activity entry.</Text></View> : null}</ScreenLayout>;
}
function messageEvent(name: string, patientId: string, message: V1FamilyMessage): Event { const status = ({ scheduled: 'scheduled', queued: 'queued', delivered: 'delivered to the device', opened: 'opened' })[message.state]; return { id: `message-${message.createdAt}-${message.messageId}`, patientId, title: 'Family message', detail: `A message for ${name} is ${status}.`, time: new Intl.DateTimeFormat('en-SG', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(message.createdAt)), icon: 'send' }; }
const styles = StyleSheet.create({ content: { gap: spacing.md, paddingTop: spacing.xl }, header: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' }, headerActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, justifyContent: 'flex-end' }, title: { color: colors.text.primary, flexShrink: 1, fontFamily: fontFamily.display, fontSize: fontSize.title, fontWeight: '500' }, filter: { alignItems: 'center', borderColor: colors.border.default, borderRadius: radius.pill, borderWidth: 1, flexDirection: 'row', gap: 6, minHeight: 44, paddingHorizontal: spacing.md }, filterText: { color: colors.accent, flexShrink: 1, fontSize: fontSize.body, fontWeight: '700' }, subtitle: { color: colors.text.secondary, flexShrink: 1, fontSize: fontSize.body, lineHeight: 22, marginBottom: spacing.xl, marginTop: spacing.md }, event: { flexDirection: 'row', gap: spacing.md }, dot: { alignItems: 'center', backgroundColor: '#EEF3E9', borderRadius: 999, flexShrink: 0, height: 34, justifyContent: 'center', marginTop: spacing.sm, width: 34 }, eventCard: { backgroundColor: colors.surface.card, borderColor: colors.border.default, borderRadius: radius.xl, borderWidth: 1, flex: 1, padding: spacing.lg }, time: { color: colors.text.secondary, flexShrink: 1, fontSize: fontSize.caption }, eventTitle: { color: colors.text.primary, flexShrink: 1, fontSize: fontSize.bodyLarge, fontWeight: '700', marginTop: 6 }, eventDetail: { color: colors.text.secondary, flexShrink: 1, fontSize: fontSize.body, lineHeight: 21, marginTop: 3 }, empty: { backgroundColor: colors.surface.card, borderColor: colors.border.default, borderRadius: radius.xl, gap: spacing.sm, padding: spacing.xl }, emptyTitle: { color: colors.text.primary, flexShrink: 1, fontFamily: fontFamily.display, fontSize: fontSize.heading }, emptyText: { color: colors.text.secondary, flexShrink: 1, fontSize: fontSize.body, lineHeight: 22 } });
