import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { AppHeader, PrimaryButton, ProvenanceSection, ScreenLayout, TertiaryButton } from '../../src/components/AppUI';
import { loadCaregiverHome, type CaregiverHomePatient } from '../../src/lib/v1Caregiver';
import { usePatientStatusV1 } from '../../src/lib/v1Client';
import { formatLastInteraction, getConversationsTodayText } from '../../src/lib/v1Status';
import { colors, fontFamily, fontSize, radius, spacing } from '../../src/theme';

export default function LovedOneDashboardScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const [person, setPerson] = useState<CaregiverHomePatient | null>(null); const [loading, setLoading] = useState(true); const status = usePatientStatusV1(id);
  const refresh = useCallback(async () => { if (!id) return; setLoading(true); try { const home = await loadCaregiverHome(); setPerson(home.patients.find((item) => item.patientId === id) || null); } finally { setLoading(false); } }, [id]);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  if (loading) return <ScreenLayout scroll={false} contentContainerStyle={styles.loading}><ActivityIndicator color={colors.accent} /></ScreenLayout>;
  if (!person) return <ScreenLayout><AppHeader title="Loved one" onBack={() => router.back()} /><Text style={styles.title}>This loved one is unavailable</Text><PrimaryButton label="Back to Home" onPress={() => router.replace('/(tabs)')} /></ScreenLayout>;
  const facts = status.data;
  const observed = !person.deviceId ? 'No device is paired yet.' : !facts ? 'No interaction data has been received from the paired device yet.' : facts.lastInteractionAt ? `Last interaction: ${formatLastInteraction(facts.lastInteractionAt)}.` : 'No interaction has been recorded yet.';
  return <ScreenLayout><AppHeader title={person.displayName} onBack={() => router.back()} /><Text style={styles.eyebrow}>Today</Text><Text accessibilityRole="header" style={styles.title}>{person.displayName}</Text><View style={styles.card}><ProvenanceSection label="Observed">{observed}</ProvenanceSection>{facts ? <ProvenanceSection label="Interaction record">{getConversationsTodayText(facts) || 'No conversation count is available yet.'}</ProvenanceSection> : null}<ProvenanceSection label="What this means">Reflexion shows only data received from the paired device. It does not infer mood, wellbeing or whether planned activities happened.</ProvenanceSection><ProvenanceSection label="Next action">{person.deviceId ? 'Leave a familiar message or review the device connection.' : 'Pair the Mirror to start receiving factual updates.'}</ProvenanceSection></View><View style={styles.actions}><PrimaryButton label={person.deviceId ? 'Leave a message' : 'Pair device'} onPress={() => router.push(person.deviceId ? `/chat/${person.patientId}/compose` : `/device/${person.patientId}/pairing`)} /></View><Text style={styles.section}>Explore</Text><View style={styles.links}><TertiaryButton label="Sessions" onPress={() => router.push(`/loved-one/${person.patientId}/sessions`)} /><TertiaryButton label="Weekly summary" onPress={() => router.push(`/loved-one/${person.patientId}/weekly-summary`)} /><TertiaryButton label="History" onPress={() => router.push(`/loved-one/${person.patientId}/history`)} /></View></ScreenLayout>;
}
const styles = StyleSheet.create({ loading: { alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: colors.accent, fontSize: fontSize.caption, fontWeight: '700', marginTop: spacing.lg }, title: { color: colors.text.primary, flexShrink: 1, fontFamily: fontFamily.display, fontSize: 26, fontWeight: '500', lineHeight: 32 }, card: { backgroundColor: colors.surface.card, borderColor: colors.border.default, borderRadius: radius.xl, borderWidth: 1, overflow: 'hidden', paddingHorizontal: spacing.lg }, actions: { gap: spacing.md }, section: { color: colors.text.primary, fontSize: fontSize.heading, fontWeight: '700', marginTop: spacing.lg }, links: { alignItems: 'flex-start', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md } });
